os: osx
script:
  - brew unlink python@2
  - brew tap VirtusLab/git-machete
  - brew install git-machete
  - git machete --version
  - brew audit --new-formula --strict git-machete
  - brew test git-machete
